apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    # This is copied from the spec > selector > matchLabels section of deployment yml file
    app: myapp
